name: Stage Deploy Website
on:
   pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Zeit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy to Zeit
        uses: amondnet/now-deployment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--target staging'

  k6_local_test:
      name: k6 Load Test
      runs-on: ubuntu-latest
      container: docker://loadimpact/k6:latest
    
      steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Local k6 test
        run: k6 run scripts/basic-load-test.js
